name: Action Test
description: 'Action Test'

inputs:
  name:
    description: 'Person to greet'
    required: true
    default: 'Mona the Octocat'

runs:
  using: "composite"
  steps:
  - name: Test Variables
    shell: bash
    run: |
      echo 1
      echo ${{ inputs.branch_name }}
      echo 2
      echo ${{ inputs.name }}
      echo 3
